### PR TITLE
Support Marshmallow

### PR DESCRIPTION
**Pull request by HridayHS**

### CODE REVIEW

**Comment by Shoaib0597** [comment]
Thanks!

**Comment by HridayHS** [comment]
Do not forgot to mention my name in Thread or to give credit :)

**Comment by Shoaib0597** [comment]
Hey, I still have a problem. After I merged your pull request from the Github Website using a Browser, I can't get the changes in my local repository. Running git status returns up-to-date. :(

**Comment by HridayHS** [comment]
Follow this :-
1. git fetch origin
2. git status
Now you can see there will be written to use git pull.
3. git pull
Done.

**Comment by Shoaib0597** [comment]
Yeah, I did that but on fetching, it is downloading around GBs. :( My internet connection isn't fast so it'll take ages for me to get hold of the new data. I thought it'll only download the additional 29 files.

**Comment by HridayHS** [comment]
Use ..
1. git fetch origin CM-13.0

**Comment by Shoaib0597** [comment]
git fetch origin CM-13.0 too was resulting in a very large download. So, I shallow-fetched the new commits to the depth of 1 which allowed me to download the new commits in seconds. :)

**Pull request merged**
